### ISSUE TITLE
Allow a user to connect their goodreads account

### ISSUE THREAD

**Issue by polygirl** [SubJunk/TimelineTools#159]
Ideas
- [ ] use Goodreads connect
- [ ] show a "want to read" visual indicator
- [ ] show a "read" visual indicator
- [ ] books can be looked up with ISBN
- [ ] the Marvel API returns the ISBN number
- [ ] let users mark things they want to read to show in XT and on goodreads
- [ ] let users mark things they have read to show in XT and on goodreads
https://www.goodreads.com/api/index#reviews.list

**Comment by SubJunk** [comment]
This would be really useful for me, might start work on it soon
