### ISSUE TITLE
Mark comics as read/unread

### ISSUE THREAD

**Issue by SubJunk** [SubJunk/TimelineTools#30]
Save as a cookie
Does an overlay on the thumbnails to track progress

**Comment by polygirl** [comment]
Also Goodreads has an API so maybe we can do some kind of matching there and if a user saves their goodreads Id we could do something smart to automatically mark them as read if they mark them as read there? https://www.goodreads.com/api/index#read_statuses.show

**Comment by SubJunk** [comment]
That would be ideal

**Comment by polygirl** [comment]
Is this what I should be reading to get started with this? https://tutorialedge.net/typescript/angular/angular-cookies-tutorial/

**Comment by SubJunk** [comment]
Actually I'm questioning whether a cookie would be a good way to do this. It should probably be more persistent.
