### ISSUE TITLE
Expanded panel should always snap inside viewport

### ISSUE THREAD

**Issue by polygirl** [SubJunk/TimelineTools#57]
When I open an expanded panel below the bottom of the screen, it does not adjust its position to inside the viewport.

If I open an expanded panel to the right of the screen, it sometimes works as expected, but sometimes doesn't depending on how close the thumbnail is to the right hand side of the screen.

Panels that open off the top of the screen and/or to the top right of the screen always display as expected.

off to the right:
![image](https://user-images.githubusercontent.com/20376562/49363917-cf739f80-f747-11e8-9cd4-b7b875265add.png)

off to the bottom:
![image](https://user-images.githubusercontent.com/20376562/49363960-eca86e00-f747-11e8-8c37-53670e05351b.png)

off to the right/bottom:
![image](https://user-images.githubusercontent.com/20376562/49364030-182b5880-f748-11e8-82b4-52199eb4873f.png)

**Comment by SubJunk** [comment]
These are good issues, and it would be good to split them out into separate issues
